# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9924fbee5c1f4e15e61625482a373be8949b8f1017b53a9dd0e329c6c2783002fab11c344129b67cde88e65258fe4c2b31a157a57146e8657628abbba629cd8a

test:
  secret_key_base: 54578f42ec6ab08c6eec3a34c976f855c4828ed9f54fcd2b23e7125877e5504371fdd25d6aad8abad8826e191dc5a975a0b964c4d92a2bd9998c921fa68ce8e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
